CREATE TABLE article_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code          VARCHAR(255)                            NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255)                            NOT NULL,
    fine          DOUBLE PRECISION                        NOT NULL,
    decision_type VARCHAR(255),
    CONSTRAINT pk_articleentity PRIMARY KEY (id)
);

CREATE TABLE court_decision_entity
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    decision_number VARCHAR(255)                            NOT NULL,
    violation_id    BIGINT,
    decision_type   VARCHAR(255)                            NOT NULL,
    fine_amount     DOUBLE PRECISION                        NOT NULL,
    comment         VARCHAR(255)                            NOT NULL,
    judge_name      VARCHAR(255)                            NOT NULL,
    decision_status VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_courtdecisionentity PRIMARY KEY (id)
);

CREATE TABLE offender_entity
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                           VARCHAR(255)                            NOT NULL,
    surname                        VARCHAR(255)                            NOT NULL,
    address                        VARCHAR(255)                            NOT NULL,
    citizenship                    VARCHAR(255)                            NOT NULL,
    personal_identification_number VARCHAR(255)                            NOT NULL,
    age                            INTEGER                                 NOT NULL,
    article_id                     BIGINT                                  NOT NULL,
    CONSTRAINT pk_offenderentity PRIMARY KEY (id)
);

CREATE TABLE violation_entity
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    offender_id  BIGINT,
    article_id   BIGINT,
    description  VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255),
    offense_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_violationentity PRIMARY KEY (id)
);

ALTER TABLE article_entity
    ADD CONSTRAINT uc_articleentity_code UNIQUE (code);

ALTER TABLE court_decision_entity
    ADD CONSTRAINT FK_COURTDECISIONENTITY_ON_VIOLATION FOREIGN KEY (violation_id) REFERENCES violation_entity (id);

ALTER TABLE offender_entity
    ADD CONSTRAINT FK_OFFENDERENTITY_ON_ARTICLE FOREIGN KEY (article_id) REFERENCES article_entity (id);

ALTER TABLE violation_entity
    ADD CONSTRAINT FK_VIOLATIONENTITY_ON_ARTICLE FOREIGN KEY (article_id) REFERENCES article_entity (id);

ALTER TABLE violation_entity
    ADD CONSTRAINT FK_VIOLATIONENTITY_ON_OFFENDER FOREIGN KEY (offender_id) REFERENCES offender_entity (id);